### ISSUE TITLE
Some questions about the file.

### ISSUE THREAD

**Issue by Wangmy1024** [whwu95/Cap4Video#1]
Good afternoon, I'm reading and trying to run your code with the file you have uploaded. But sorry, I didn't successfully run this code, maybe it's because of file “sim_matrix” is not provided. Besides, may I ask when the pre-extracted video frame features will be uploaded? Hope for your reply and may you good journey.

**Comment by whwu95** [comment]
Thank you for your interest in our work! 
I just wanted to let you know that we have uploaded the pre-extracted MSRVTT Frames, which you can find in the readme. Additionally, our sim_matrix has also been uploaded.

**Comment by Wangmy1024** [comment]
Thanks for your reply!

**Comment by shams2023** [comment]
> Thanks for your reply!

你好，请问这个代码该如何运行？
