### ISSUE TITLE
How the entire dataset is converted into captions

### ISSUE THREAD

**Issue by shams2023** [whwu95/Cap4Video#11]
Thank you very much for your work!
How do you convert a video from an entire dataset into captions? I currently want to convert all the images or videos in the entire dataset into captions, but the code involved in the article [ZeroCap: Zero Shot Image to Text Generation for Visual Semantic Arithmetic] only works by converting one image into captions, so I really want to know what I need to do if I want to convert an entire dataset?
I really hope to receive your guidance. Thank you again

**Comment by whwu95** [comment]
Please refer to https://github.com/YoadTew/zero-shot-video-to-text for generating video captions.
