### ISSUE TITLE
Requesting code to generate the frames from the MSRVTT dataset

### ISSUE THREAD

**Issue by fazlicodes** [whwu95/Cap4Video#21]
Hi, I've been trying to unzip the frames_30fps.zip for the past 2 days but its very slow and often gets disrupted. Could you please provide me the code to generate the frames_30fps using the MSRVTT video dataset as input

**Comment by shams2023** [comment]
> Hi, I've been trying to unzip the frames_30fps.zip for the past 2 days but its very slow and often gets disrupted. Could you please provide me the code to generate the frames_30fps using the MSRVTT video dataset as input

Communication?

**Comment by whwu95** [comment]
Please refer to the script for extracting frames from video at [video2image.py](https://github.com/whwu95/Cap4Video/blob/main/video2image.py), with an FPS of 30.
