### ISSUE TITLE
Python, Pytorch, Torchvision, Cudatoolkit versions

### ISSUE THREAD

**Issue by dumbelldore** [whwu95/Cap4Video#22]
Unable to train the model, I think the library versions are not compatible.
I'm getting the following error:
unrecognized arguments: --local_rank

**Comment by ericyq** [comment]
pip install torch==1.8.1+cu111 torchvision==0.9.1+cu111 torchaudio==0.8.1 -f https://download.pytorch.org/whl/torch_stable.html
