### ISSUE TITLE
some questions

### ISSUE THREAD

**Issue by shams2023** [whwu95/Cap4Video#24]
![image](https://github.com/whwu95/Cap4Video/assets/141383792/aaeb1359-9056-4934-bf24-1c6699d47c29)
这里面的C指的是这个视频生成的辅助字幕的数量吗？
我看最后做消融实验的时候说最好的结果是1个辅助字幕就会得到很好的结果
所以这个C该如何理解

**Comment by whwu95** [comment]
C是caption的数量，“我看最后做消融实验的时候说最好的结果是1个辅助字幕就会得到很好的结果”这里可能有误会哈，这里是指caption用于与video构建额外正样本对时（即caption三个功能中的input阶段），只用1个就行。
