### ISSUE TITLE
Preprocess for other datasets

### ISSUE THREAD

**Issue by battlezzq** [whwu95/Cap4Video#25]
Hi, it's a good work!
I want to run the code on other video retrieval datasets, therefore I wonder know that how to convert the raw video into frame.
Such as the sample rate, size of every frames in your code.

**Comment by whwu95** [comment]
Please refer to the script for extracting frames from video at [video2image.py](https://github.com/whwu95/Cap4Video/blob/main/video2image.py), with an FPS of 30.
