### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'data/MSRVTT_test_website_titles.json'

### ISSUE THREAD

**Issue by THU-Kingmin** [whwu95/Cap4Video#29]
![screenshot-20240705-114831](https://github.com/whwu95/Cap4Video/assets/43465723/599b43dd-0ebc-4d18-9581-0b0bd07e94c3)
请问一下MSRVTT_test_website_titles在哪里下载呀

**Comment by cathy345345** [comment]
找到了吗？我也找不到

**Comment by whwu95** [comment]
Please refer to https://github.com/whwu95/Cap4Video/releases/tag/v1.1
