### ISSUE TITLE
Question of the caption file.

### ISSUE THREAD

**Issue by JosephPai** [whwu95/Cap4Video#5]
Hi,

Thanks for releasing the code and data.
I have checked the provided caption data and I found that there are two additional keys in the dataset, 'title' and 'titles'.
Can you provide some explanation about them? Like how did you get the data, from url or captioning model? And what is the difference between the two sets?

Thank you!

**Comment by whwu95** [comment]
Hi,

The key 'title' refers to the query in the original dataset's query-video pair. It represents the textual input or query associated with a particular video. On the other hand, the key 'titles' refers to multiple captions generated by a zero-shot captioning model specifically for that video. These captions provide additional textual descriptions or interpretations of the video content.

Please let me know if you have any further questions

**Comment by JosephPai** [comment]
Hi,

Thanks for your response.

If I understand correctly, in Table 5 ablation study of different number of captions for data augmentation, the top-1 result comes from the 'title' key, while the top-3 and top-5 come from the 'titles' key, right?

If so, are the multiple captions in the 'titles' organized in the order sorted by CLIP similarity?

Thank you!

**Comment by whwu95** [comment]
> Hi,
> 
> Thanks for your response.
> 
> If I understand correctly, in Table 5 ablation study of different number of captions for data augmentation, the top-1 result comes from the 'title' key, while the top-3 and top-5 come from the 'titles' key, right?
> 
> If so, are the multiple captions in the 'titles' organized in the order sorted by CLIP similarity?
> 
> Thank you!

Yes, you are right.
